function V = G_vectorize...
    (Gnet,geneList,reference,numberOfVectors,useGPU)
%G_VECTORIZE    Vectorize the reference sample group into 64 dimentional
%   vector(s). The vector is for the entire group because, because the
%   group variance of genes are also considered in vectorization.
%   user can also use a numberOfVectors larger than 1 and the vector would
%   be generated by random resampling.
%   author: Zhaozheng Hou (George)
%
% V = G_vectorize(Gnet,geneList,reference,numberOfVectors,useGPU)
% parameter:
%   - Gnet: generator network to use (network or the name of trained
%       network, such as "BGPP10" for "the generator for bulk-RNA seq
%       data with predefined pathways and using 10 references")
%   - geneList: list of genes (strings or numbers), leave blank and skip
%       the matching if the data already matched the gene list
%   - reference: expression of smples, each column is one
%       sample. At least 2 samples.
%   - numberOfVectors: number of vectors to generate, 1 by default.
%   - useGPU: (optional) whether using GPU for the processing or not, false
%       by default.
% output:
%   - V: each column is one vectorized result

%% validate
if (isa(Gnet,"dlnetwork"))
    validateattributes(Gnet,{'dlnetwork'},{'scalar'});
else
    validateattributes(Gnet,{'string','char'},{'scalartext'});
    Gnet=load("core\"+string(Gnet)+".mat",string(Gnet));
    Gnet=struct2cell(Gnet);
    Gnet=Gnet{1};
end
n=Gnet.getLayer(Gnet.InputNames{1}).InputSize;

if (isempty(geneList))
    geneList=nan(n(1),1);
else
    validateattributes(geneList,{'numeric','char','string'},{'vector'});
end
validateattributes(reference,{'numeric'},{'nonnegative','size',[numel(geneList),nan]});
validateattributes(size(reference,2),{'numeric'},{'>=',2});

if (nargin>=4)
    validateattributes(numberOfVectors,{'numeric'},{'integer','positive'});
    if (isempty(numberOfVectors))
        numberOfVectors=1;
    end
else
    numberOfVectors=1;
end

if (nargin>=5)
    validateattributes(useGPU,{'numeric','logical'},{'binary'});
    if (isempty(useGPU))
        useGPU=false;
    end
else
    useGPU=false;
end

if (~Gnet.Initialized)
    warning("The network is not yet initialized. Initializing now...");
    Gnet=Gnet.initialize;
end

%% process
sizeOfReference=size(reference,2);

% match genes
if (~isnan(geneList))
    [netGeneID,listGeneID] = match_gene_list(geneList);
    temp=zeros(n(1),sizeOfReference);
    temp(netGeneID,:)=reference(listGeneID,:);
    reference=temp;
end

% prepare references
if (numberOfVectors==1)
    % only one vector for the given reference
    if (sizeOfReference<=n(2))
        % no need to repeat
        sid=repmat(1:sizeOfReference,n(2));
        reference=dlarray(reference(:,sid(1:n(2))),'SSCB');
    else
        % need to resample and calculate average
        sid=[(1:sizeOfReference)',...
            ceil(sizeOfReference*rand(sizeOfReference,n(2)-1))];
        reference=reshape(reference(:,sid'),[n(1),n(2),1,sizeOfReference]);
        reference=dlarray(reference,'SSCB');
    end
else
    sid=ceil(sizeOfReference*rand(numberOfVectors,n(2)));
    reference=reshape(reference(:,sid'),[n(1),n(2),1,numberOfVectors]);
    reference=dlarray(reference,'SSCB');
end
if (useGPU)
    try
        reference=gpuArray(reference);
    catch
        warning("Error when using GPU, trying with CPU...");
        useGPU=false;
    end
end

% calculate V
try
    V=predict(Gnet,reference,outputs='batchnorm_4').gather.extractdata;
catch ME % try to solve if GPU is the reason of exception
    if (useGPU)
        reference=reference.gather;
        V=predict(Gnet,reference,outputs='batchnorm_4').extractdata;
        warning("Error when using GPU, and problem solved by using CPU.")
    else
        rethrow(ME)
    end
end
if (numberOfVectors==1)
    V=mean(V,2);
end
end